In [1]:
import numpy as np
import pandas as pd

## arange

In [2]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

## linespace

In [6]:
np.linspace(0,10,5)
# linspace(start,end,range)
# create items equale to the range between two number
# it can create float number or integers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Series

In [7]:
pd.Series({"name":"Ghyath","surname":"Moussa","age":23})

name       Ghyath
surname    Moussa
age            23
dtype: object

In [8]:
pd.DataFrame(pd.Series(data=["ghyath","Moussa"],index=[1,2]))

0
1  ghyath
2  Moussa

## Data Frame

In [9]:
arr = np.random.randn(5,5)

In [10]:
arr = pd.DataFrame(arr)

## Pandas Important Functions